name: Generate Snake Animation

on:
  # Run this workflow automatically on a schedule
  schedule:
    - cron: "0 6 * * *" # Runs every day at 6 AM

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          # Your GitHub username
          github_user_name: uchamod

          # The output file for the animation
          outputs: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
